{% set version = "4.0.3" %}
{%set sha256 = "680153225128900dbf1b063a2915fcc6bd6c00188513bb74bed52393e1a2a7c0" %}

package:
  name: libconda
  version: {{ version }}

source:
  fn: libconda-{{ version }}.tar.gz
  url: https://github.com/conda/libconda/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python
    - pycosat >=0.6.1
    - pyyaml
    - requests

test:
  imports:
    - libconda
    - libconda.progressbar

about:
  home: https://github.com/conda/libconda
  license: BSD 3-Clause
  summary: conda 4.0 based library

extra:
  recipe-maintainers:
    - jakirkham
